### ISSUE TITLE
Stuck at thinking 

### ISSUE THREAD

**Issue by itsmo-ks** [TBXark/poe-telegram-bot#1]
![Screenshot_2023-04-11-19-58-13-413-edit_uz unnarsx cherrygram](https://user-images.githubusercontent.com/62901183/231274907-a0377365-994f-45be-8945-096fd3946b3f.jpg)
After using it for a while the bot stuck at thinking, and i can't use it anymore until i restart the bot , I'm using it on a vps

**Comment by mohamedkaissi** [comment]
And this error everttime the bot send a msg.

https://pastebin.com/GJeQSjWr

**Comment by TBXark** [comment]
Maybe your token is invalid, you can use `/token new_token` to replace the token.

**Comment by TBXark** [comment]
It is also possible that your account is invalid, please go to the web version to confirm. Because this usage is not legal, it can easily lead to being banned.

**Comment by mohamedkaissi** [comment]
The account is still working, the bot will work normally after I restart

**Comment by mohamedkaissi** [comment]
[poe-poe-bot-e20be64b-05b0-4edc-91bb-ca3a2450a6af.txt](https://github.com/TBXark/poe-telegram-bot/files/11210586/poe-poe-bot-e20be64b-05b0-4edc-91bb-ca3a2450a6af.txt)

**Comment by TBXark** [comment]
Seems to be caused by ws randomly failing without an effective reconnection mechanism. I can try to fix it later.

**Comment by TBXark** [comment]
I added a command to `/reconnect` so the conversation can continue.

**Comment by bolavefasfas** [comment]
> I added a command to `/reconnect` so the conversation can continue.

can add all bot commands in readme.md file please and update the repo its so useful as we connot get gpt4 api through open ai but we can use it through poe its a lot easier and about multi user support for bot ?

**Comment by TBXark** [comment]
> can add update the repo as many users cannot get gpt4 api through open ai but we can use it through poe its a lot easier beacuse of your bot ?
> 
> Amazing work !!


POE free users can only use GPT4 once a day, you can use `/models` to get the ID of GPT4 bot. then use `/model bot_name` to switch.
