### ISSUE TITLE
Support for multiple Telegram user IDs

### ISSUE THREAD

**Issue by danxxcruz** [TBXark/poe-telegram-bot#3]
Please add support for multiple Telegram users to chat with same bot. Also to be able to use it in groups.

**Comment by TBXark** [comment]
The api is unstable due to POE's policy, so I probably won't spend much effort on this repo. You can try another project of mine: https://github.com/TBXark/telegram-bot-go

**Comment by danxxcruz** [comment]
Didn't know about the issue with Poe's API, I liked this project since I don't have a OpenAI account and therefore don't have access to an OpenAI API key, also ChatGPT's web isn't available in my country. Thanks anyway. Nice job

**Comment by TBXark** [comment]
If you only want to use poe, you can try this project https://github.com/zhayujie/bot-on-anything. But it's a bit cumbersome to deploy.

**Comment by danxxcruz** [comment]
Thanks, I will check it out. Closing issue.

**Comment by TBXark** [comment]
sorry wrong repo.  this one : https://github.com/lss233/chatgpt-mirai-qq-bot
