### ISSUE TITLE
Response stuck on (Loading...) on long messages

### ISSUE THREAD

**Issue by danxxcruz** [TBXark/poe-telegram-bot#5]
![Screenshot_20230429-024154.png](https://user-images.githubusercontent.com/93965387/235288073-fe9fd77f-7b9b-4a67-90c6-9bc5f01ef0ff.png)

**Comment by TBXark** [comment]
cloudflare cpu time limit exceeded

**Comment by TBXark** [comment]
maybe ws is broken

**Comment by TBXark** [comment]
Can the new conversation continue? If it can continue, perhaps it has been truncated due to exceeding the token length limit.

**Comment by danxxcruz** [comment]
I'm sorry what does ws stands for? Is there a workaround for that? 😅

**Comment by danxxcruz** [comment]
> Can the new conversation continue? If it can continue, perhaps it has been truncated due to exceeding the token length limit.

Yes the conversation continues as normally, in the WebApp the bot shows the full message normally when asked a similar prompt.

**Comment by TBXark** [comment]
> I'm sorry what does ws stands for? Is there a workaround for that? 😅

web-socket, If you cannot continue the conversation, it is caused by the disconnection of the web-socket.

**Comment by TBXark** [comment]
> 

Then it may have been truncated because it was too long. You can check the same history on the POE web of the same account to see if it is also truncated.

**Comment by danxxcruz** [comment]
> > 
> 
> Then it may have been truncated because it was too long. You can check the same history on the POE web of the same account to see if it is also truncated.

On the web interface the message is shown complete
![Screenshot_20230429-113426.png](https://user-images.githubusercontent.com/93965387/235310999-e692c00a-cad9-4871-9e1a-06760b398e26.png)

**Comment by TBXark** [comment]
There are two possibilities, one is that the length exceeds the limit of the telegram message length. The second is that it is so long that the number of refreshes exceeds the limit of telegram. You can try if this complete message can be sent at once in telegram.

**Comment by danxxcruz** [comment]
It seems that is not length limit as in the example I shown the length is 2741 and the Telegram limit is 4K characters.

**Comment by reonjy112** [comment]
also experience this, what i did is to temporarily disable the message streaming, so the bot will reply the complete response just the same on the web page

**Comment by danxxcruz** [comment]
How did you modified the code to accomplish that?

**Comment by reonjy112** [comment]
> How did you modified the code to accomplish that?

try to replace this as main.py https://dropden.com/fbf07ff2fc49

**Comment by danxxcruz** [comment]
> try to replace this as main.py https://dropden.com/fbf07ff2fc49 take note that non-streaming text make take 5-10 secs to reply depending on how long the response but it should give you a complete response.

Yup! Worked for me. Thanks! Closing issue i guess 💯

**Comment by TBXark** [comment]
But there is no stream mode after making these modifications. You can try adjusting the refresh rate from 25 to a larger number and see if it works.
https://github.com/TBXark/poe-telegram-bot/blob/7c26a44d1ac87943736b586ffee2dfc9c9cf4cbb/main.py#L107

**Comment by TBXark** [comment]
I made a slight change to make the refresh rate slower and reduce the number of times long texts are refreshed.

**Comment by reonjy112** [comment]
> I made a slight change to make the refresh rate slower and reduce the number of times long texts are refreshed.

thanks, it works fine now.. :)
